import type { EditorialEntry } from '@/lib/content/types';

export const newsEntries: EditorialEntry[] = [
  {
    id: 'news-convergence-festival-lineup',
    section: 'news',
    title: 'Convergence Festival Reveals Creator-First Lineup for Fall',
    slug: 'convergence-festival-creator-first-lineup',
    excerpt:
      'The annual event shifts toward director and showrunner showcases, giving fans deeper access to the people behind major franchises.',
    publishedAt: '2026-04-28',
    authorId: 'maya-lane',
    categories: ['Events', 'Industry'],
    tags: ['festival', 'creators', 'panels'],
    featuredImage: 'Neon-lit convention stage with panel lights',
    readingTimeMinutes: 5,
    status: 'published',
    body: [
      'Convergence Festival announced a stronger creator-focused program this year, prioritizing writer rooms, production design showcases, and behind-the-scenes process sessions.',
      'Organizers said the move responds to fan demand for context and craft, not just trailer reveals. Several major studios are also piloting longer Q&A formats with moderated editorial hosts.',
      'For Nerd Cluster readers, the shift marks a useful trend: fandom events are maturing into spaces where storytelling process matters as much as headline announcements.',
    ],
  },
  {
    id: 'news-collector-wave-signal-series',
    section: 'news',
    title: 'Signal Series Collector Wave Adds Numbered Deluxe Variant',
    slug: 'signal-series-collector-wave-deluxe-variant',
    excerpt:
      'The latest run introduces serialized packaging and expanded accessory sets aimed at long-term collectors.',
    publishedAt: '2026-04-25',
    authorId: 'maya-lane',
    categories: ['Collectibles'],
    tags: ['figures', 'limited', 'collector-market'],
    featuredImage: 'Collector shelf featuring premium boxed figures',
    readingTimeMinutes: 4,
    status: 'published',
    body: [
      'Manufacturers are increasingly treating premium variants as archival products rather than short-term novelty drops.',
      'This new Signal Series run includes serialized certificates, alternate sculpt details, and a stronger preservation-friendly packaging profile.',
      'Retail analysts expect demand to skew toward core collectors who prioritize display quality, long-term value retention, and lore relevance.',
    ],
  },
  {
    id: 'news-streaming-anthology-window',
    section: 'news',
    title: 'Three Genre Anthologies Target Staggered Weekly Windows',
    slug: 'three-genre-anthologies-staggered-weekly-windows',
    excerpt:
      'Studios are testing release pacing built around discourse durability rather than weekend spikes.',
    publishedAt: '2026-04-22',
    authorId: 'jules-orozco',
    categories: ['Streaming'],
    tags: ['anthology', 'release-strategy', 'audience-behavior'],
    featuredImage: 'Streaming control room dashboard with release calendar',
    readingTimeMinutes: 6,
    status: 'published',
    body: [
      'The anthology strategy appears designed to generate sustained conversation cycles rather than immediate completion metrics.',
      'Executives pointed to stronger episode-level engagement when release cadence leaves room for reaction, theory-building, and creator commentary.',
      'For editorial sites, this format creates an opportunity for richer weekly coverage that mixes criticism, analysis, and fan-context reporting.',
    ],
  },
  {
    id: 'news-phase7-lineup-leak',
    section: 'news',
    title: 'Phase 7 Slate Leak Sends Fan Theory Threads Into Overdrive',
    slug: 'phase-7-slate-leak-fan-theory-threads',
    excerpt:
      'An alleged internal document circulating online describes a multi-year release arc and several unexpected casting callouts.',
    publishedAt: '2026-04-20',
    authorId: 'maya-lane',
    categories: ['Movies', 'Industry'],
    tags: ['leak', 'franchise', 'casting'],
    featuredImage: 'Film slate board under dramatic studio lighting',
    readingTimeMinutes: 5,
    status: 'published',
    body: [
      'Whether it is authentic or an elaborate fan construction, the document has already reshaped discussion on major forums, with specific character callouts generating hundreds of theory threads.',
      'Studios have declined to comment, which in practice functions as its own form of engagement — silence extends the discourse cycle rather than ending it.',
      'The real signal here is that audiences are hungry for long-arc franchise transparency. When official communication lags, speculation fills the gap.',
    ],
  },
  {
    id: 'news-nintendo-crossover-direct',
    section: 'news',
    title: 'Summer Direct Teases Unexpected Cross-Universe Collaboration',
    slug: 'summer-direct-cross-universe-collaboration',
    excerpt:
      'A brief end-of-show tease at this week\'s showcase left audiences with more questions than answers and a very specific set of expectations.',
    publishedAt: '2026-04-18',
    authorId: 'rowan-kent',
    categories: ['Games', 'Industry'],
    tags: ['direct', 'crossover', 'gaming-news'],
    featuredImage: 'Game showcase stage with dramatic spotlight reveal',
    readingTimeMinutes: 4,
    status: 'published',
    body: [
      'The tease lasted under thirty seconds: a logo animation, a familiar musical motif from an unexpected source, and a release window that simply read "When it is ready."',
      'Fan response online split immediately between those reading it as confirmation of a long-rumored collaboration and those cautioning that a tease this minimal is designed to generate exactly this conversation.',
      'Either way, it worked. The showcase segment is the most clipped and reposted moment from this year\'s summer event cycle.',
    ],
  },
  {
    id: 'news-steelbook-packaging-trend',
    section: 'news',
    title: 'Steelbook Packaging Is Winning the Physical Media Shelf Wars',
    slug: 'steelbook-packaging-winning-physical-media-shelf-wars',
    excerpt:
      'Collector data and retail trends suggest premium packaging formats are outpacing standard releases among enthusiast buyers.',
    publishedAt: '2026-04-15',
    authorId: 'maya-lane',
    categories: ['Collectibles', 'Industry'],
    tags: ['steelbook', 'physical-media', 'collector-market'],
    featuredImage: 'Row of steelbook editions with foil art on a collector shelf',
    readingTimeMinutes: 5,
    status: 'published',
    body: [
      'Physical media was supposed to be dying. Instead, a specific segment of it — premium collector editions with strong art direction — appears to be gaining ground.',
      'Specialty retailers report that steelbook and lenticular editions regularly sell through faster than standard releases within the enthusiast buying window.',
      'The underlying behavior is about identity and display, not just archival instinct. People are curating visible shelves, and standard plastic cases do not fit that story.',
    ],
  },
  {
    id: 'news-amazon-scifi-anthology',
    section: 'news',
    title: "Amazon's New Sci-Fi Anthology: Everything Confirmed So Far",
    slug: 'amazon-scifi-anthology-everything-confirmed',
    excerpt:
      'A prestige-positioned sci-fi anthology series has cleared casting and production start dates, with a line-up that includes several unexpected genre names.',
    publishedAt: '2026-04-12',
    authorId: 'jules-orozco',
    categories: ['TV', 'Streaming'],
    tags: ['amazon', 'sci-fi', 'anthology', 'casting'],
    featuredImage: 'Space-lit production set with dramatic overhead rigging',
    readingTimeMinutes: 6,
    status: 'published',
    body: [
      'The anthology format allows the series to operate without the continuity constraints that typically slow franchise television, giving each episode a self-contained tone.',
      'The confirmed directing lineup includes several names associated with high-craft genre work, which suggests the brief to writers was ambitious rather than purely commercial.',
      'Release window is currently listed for late 2026, but anthology production is historically unpredictable. One strong episode can reshape the entire conversation around a show.',
    ],
  },
  {
    id: 'news-draft-collector-market-forecast',
    section: 'news',
    title: 'Collector Market Forecast: What Summer Waves Might Look Like',
    slug: 'collector-market-forecast-summer-waves',
    excerpt: 'Early channel chatter suggests summer product waves may pivot toward smaller serialized drops.',
    publishedAt: '2026-04-29',
    authorId: 'maya-lane',
    categories: ['Collectibles'],
    tags: ['market', 'forecast', 'draft'],
    featuredImage: 'Draft board with collectible release projections',
    readingTimeMinutes: 5,
    status: 'draft',
    body: [
      'This draft entry is intentionally unpublished and should never surface on public routes, listings, sitemap output, or homepage selections.',
      'It exists to harden launch behavior around editorial visibility and prevent accidental pre-publication exposure.',
      'Finalize this story only after sourcing is complete and status is switched to published in a separate editorial workflow step.',
    ],
  },
];
