import type { ReviewEntry } from '@/lib/content/types';

export const reviewEntries: ReviewEntry[] = [
  {
    id: 'review-eclipse-protocol',
    section: 'reviews',
    title: 'Review: Eclipse Protocol Balances Tension, Tactics, and Heart',
    slug: 'review-eclipse-protocol-tactics-and-heart',
    excerpt: 'A cerebral sci-fi thriller with meaningful systems depth and character beats that actually land.',
    publishedAt: '2026-04-27',
    authorId: 'rowan-kent',
    categories: ['Games'],
    tags: ['strategy', 'sci-fi', 'single-player'],
    featuredImage: 'Tactical hologram battlefield with deep space backdrop',
    readingTimeMinutes: 8,
    status: 'published',
    score: 8.8,
    verdict: 'Essential for strategy fans who want narrative payoff.',
    body: [
      'Eclipse Protocol succeeds because it trusts players to think, adapt, and accept tradeoffs. Systems interlock cleanly without becoming opaque.',
      'The campaign framing is more intimate than expected, using mission fallout and crew dynamics to create emotional momentum between set pieces.',
      'Its few pacing dips do not undercut the broader achievement: this is a confident genre release with staying power beyond launch week.',
    ],
  },
  {
    id: 'review-vault-riders-season1',
    section: 'reviews',
    title: 'Review: Vault Riders Season 1 Is Stylish but Structurally Uneven',
    slug: 'review-vault-riders-season-1-structurally-uneven',
    excerpt: 'An art-direction standout with strong midseason episodes, held back by rushed connective arcs.',
    publishedAt: '2026-04-24',
    authorId: 'rowan-kent',
    categories: ['TV'],
    tags: ['streaming', 'sci-fi', 'series-review'],
    featuredImage: 'Futuristic city skyline with elevated rail and neon glow',
    readingTimeMinutes: 7,
    status: 'published',
    score: 7.4,
    verdict: 'Worth watching for visuals and standout episodes.',
    body: [
      'Vault Riders opens with impressive visual confidence, especially in production design and costume language that helps worldbuilding feel tactile.',
      'The strongest episodes focus on character pairings and moral ambiguity, while the weakest rely too heavily on exposition and rapid resets.',
      'Season 2 has real potential if the writers commit to consequence and let arcs breathe instead of constantly accelerating to the next reveal.',
    ],
  },
  {
    id: 'review-resonance-collectors-set',
    section: 'reviews',
    title: 'Review: Resonance Collector Set Nails Presentation, Misses Practicality',
    slug: 'review-resonance-collector-set-presentation-practicality',
    excerpt: 'A premium package with excellent art direction and mixed day-to-day usability.',
    publishedAt: '2026-04-21',
    authorId: 'maya-lane',
    categories: ['Collectibles'],
    tags: ['physical-media', 'collector-edition', 'design'],
    featuredImage: 'Collector box set with embossed metallic slipcase',
    readingTimeMinutes: 6,
    status: 'published',
    score: 7.9,
    verdict: 'Great display piece, imperfect utility object.',
    body: [
      'The Resonance set is one of the better-looking collector releases this year, with premium materials and cohesive visual storytelling across inserts.',
      'Practical pain points appear quickly: tight tray tolerances, fragile foldouts, and a display stand that feels under-tested.',
      'For display-first collectors this is still an appealing pickup, but archival-minded buyers may want additional protective storage.',
    ],
  },
  {
    id: 'review-outer-reaches-episode-one',
    section: 'reviews',
    title: 'Review: The Outer Reaches Pilot Is Atmospheric, Deliberate, and Worth the Patience',
    slug: 'review-outer-reaches-pilot-atmospheric-deliberate',
    excerpt:
      'A slow-burn sci-fi opener that trusts its tone over its plot, rewarding viewers who let it breathe.',
    publishedAt: '2026-04-19',
    authorId: 'rowan-kent',
    categories: ['TV'],
    tags: ['streaming', 'sci-fi', 'pilot', 'slow-burn'],
    featuredImage: 'Isolated space station in a vast cosmic environment',
    readingTimeMinutes: 7,
    status: 'published',
    score: 8.2,
    verdict: 'A confident, atmospheric pilot that earns its slow pace.',
    body: [
      'The Outer Reaches opens not with action but with silence — a long tracking shot through an empty corridor, scored almost entirely with ambient resonance.',
      'This is not the show for viewers who need immediate stakes. It is the show for viewers who want to inhabit a space before the story forces them to care about it.',
      'The writing is restrained in a way that feels intentional rather than incomplete. Enough is withheld that the second episode will determine whether this patience is structural or stalling.',
    ],
  },
  {
    id: 'review-phantom-protocol-collector',
    section: 'reviews',
    title: 'Review: Phantom Protocol Collector Edition Is Built for the Shelf, Not the Drawer',
    slug: 'review-phantom-protocol-collector-edition-built-for-shelf',
    excerpt: 'A strong premium package with thoughtful extras — let down only by packaging that prioritizes look over longevity.',
    publishedAt: '2026-04-16',
    authorId: 'maya-lane',
    categories: ['Collectibles', 'Games'],
    tags: ['collector-edition', 'physical-media', 'limited-run'],
    featuredImage: 'Phantom Protocol collector edition box with holographic sleeve art',
    readingTimeMinutes: 6,
    status: 'published',
    score: 8.5,
    verdict: 'Shelf-worthy. Handle the outer sleeve with care.',
    body: [
      'The extras package here is genuinely considered: a concept art booklet with real print quality, a soundtrack disc that does not feel like an afterthought, and a numbered authentication card printed on stock heavy enough to feel intentional.',
      'The box itself is the problem — the magnetic closure is satisfying, but the rigid outer sleeve has already shown stress creases in multiple early-production copies.',
      'If you are buying this to display, be aware. If you are buying it to archive, invest in a protective sleeve immediately.',
    ],
  },
  {
    id: 'review-starfall-chronicles',
    section: 'reviews',
    title: 'Review: Starfall Chronicles Swings Big on World-Building, Stumbles on Pacing',
    slug: 'review-starfall-chronicles-world-building-pacing',
    excerpt:
      'An ambitious RPG with a spectacular lore foundation undercut by uneven moment-to-moment design.',
    publishedAt: '2026-04-10',
    authorId: 'rowan-kent',
    categories: ['Games'],
    tags: ['rpg', 'open-world', 'lore-heavy'],
    featuredImage: 'Vast fantasy landscape with dual-sun sky and ancient ruins',
    readingTimeMinutes: 9,
    status: 'published',
    score: 7.1,
    verdict: 'Worth it for lore-first players. Others may need patience.',
    body: [
      'The world in Starfall Chronicles is one of the most densely annotated in recent memory — every region has history, every faction has factions within it, and the library mechanic rewards obsessive readers.',
      'Unfortunately the game surrounding that world does not always match its ambition. The pacing in acts two and three slows to a crawl, with mandatory travel sequences that feel like they exist because the map is large, not because the game wanted them.',
      'The ending recovers most of the goodwill. If you are the kind of player who reads every tooltip and optional lore fragment, this will feel essential. If you are not, it will feel very long.',
    ],
  },
];
