import type { ProductMeta } from '@/lib/content/types';

export const storeProducts: ProductMeta[] = [
  {
    id: 'store-neon-district-figure',
    name: 'Neon District Sentinel Figure',
    slug: 'neon-district-sentinel-figure',
    tagline: 'Premium articulated display figure with district-runner gear set.',
    description:
      'A collectible-first release inspired by cyberpunk city epics. Includes alternate visor sculpts, weathered accessories, and a magnetic base plate for shelf-safe posing.',
    price: '$129',
    category: 'Collectibles',
    franchise: 'Neon District',
    type: '1/10 Scale Figure',
    image: 'Neon-lit collector figure posed on a rooftop display base',
    imageAlt: 'Neon District Sentinel figure with alternate gear loadout',
    availability: 'available',
    featured: true,
    externalUrl: 'https://shop.example.com/products/neon-district-sentinel-figure',
    ctaLabel: 'Buy from Partner',
    tags: ['limited-run', 'display-piece', 'cyberpunk'],
  },
  {
    id: 'store-echoes-vinyl-ost',
    name: 'Echoes of Titan Deluxe Vinyl OST',
    slug: 'echoes-of-titan-deluxe-vinyl-ost',
    tagline: 'Triple-LP score pressing with director and composer liner notes.',
    description:
      'A heavyweight vinyl package for soundtrack collectors who care about mastering quality and sleeve art. Includes a foldout timeline insert and numbered stamp.',
    price: '$74',
    category: 'Books & Art',
    franchise: 'Echoes of Titan',
    type: 'Collector Vinyl',
    image: 'Triple vinyl set with cinematic sleeve art and foil title treatment',
    imageAlt: 'Echoes of Titan deluxe vinyl package with opened gatefold',
    availability: 'preorder',
    featured: true,
    externalUrl: 'https://shop.example.com/products/echoes-of-titan-deluxe-vinyl-ost',
    ctaLabel: 'Preorder Now',
    tags: ['soundtrack', 'numbered', 'art-booklet'],
  },
  {
    id: 'store-lore-archive-hardcover',
    name: 'Franchise Lore Archive Vol. 1',
    slug: 'franchise-lore-archive-vol-1',
    tagline: 'Hardcover canon companion built for lore-minded readers.',
    description:
      'An editorial-style reference volume featuring timeline maps, creator interviews, and archival visuals spanning the first era of the franchise universe.',
    price: '$48',
    category: 'Books & Art',
    franchise: 'Starline Continuum',
    type: 'Hardcover Compendium',
    image: 'Hardcover lore compendium open beside timeline cards and annotations',
    imageAlt: 'Franchise lore archive hardcover on a collector desk',
    availability: 'available',
    externalUrl: 'https://shop.example.com/products/franchise-lore-archive-vol-1',
    ctaLabel: 'Shop Book',
    tags: ['worldbuilding', 'reference', 'collector-library'],
  },
  {
    id: 'store-arcade-club-jacket',
    name: 'Retro Arcade Club Varsity Jacket',
    slug: 'retro-arcade-club-varsity-jacket',
    tagline: 'Premium heavyweight jacket with stitched icon patches.',
    description:
      'Streetwear-forward apparel with collector energy. Tailored fit, satin lining, and franchise patchwork designed for convention and everyday wear.',
    price: '$168',
    category: 'Apparel',
    franchise: 'Arcade Club',
    type: 'Outerwear',
    image: 'Black and violet varsity jacket with embroidered arcade iconography',
    imageAlt: 'Retro Arcade Club varsity jacket on mannequin display',
    availability: 'available',
    externalUrl: 'https://shop.example.com/products/retro-arcade-club-varsity-jacket',
    ctaLabel: 'View Sizing & Buy',
    tags: ['streetwear', 'embroidered', 'premium'],
  },
  {
    id: 'store-studio-lightbox',
    name: 'Studio Scene Lightbox Frame',
    slug: 'studio-scene-lightbox-frame',
    tagline: 'Backlit frame made for premium poster and concept art display.',
    description:
      'A shelf and wall-ready frame system for collectors who rotate art prints. Features dimmable lighting presets and cable channels for clean setups.',
    price: '$96',
    category: 'Home & Display',
    franchise: 'Nerd Cluster Essentials',
    type: 'Display Hardware',
    image: 'Backlit concept art frame glowing on a dark media room wall',
    imageAlt: 'Studio Scene Lightbox displaying character concept art',
    availability: 'available',
    tags: ['display', 'decor', 'collector-setup'],
  },
  {
    id: 'store-saga-controller-dock',
    name: 'Saga Controller Dock Set',
    slug: 'saga-controller-dock-set',
    tagline: 'Magnetic dual-controller dock with franchise crest faceplate.',
    description:
      'Designed for gaming stations where presentation matters. Includes swappable crests, braided cable routing, and anti-slip weighted base.',
    price: '$62',
    category: 'Gaming Accessories',
    franchise: 'Mythic Saga',
    type: 'Desk Accessory',
    image: 'Dual controller dock with glowing franchise crest accents',
    imageAlt: 'Saga dock holding two controllers in illuminated stand',
    availability: 'available',
    externalUrl: 'https://shop.example.com/products/saga-controller-dock-set',
    ctaLabel: 'Buy Accessory',
    tags: ['gaming-setup', 'desk', 'licensed'],
  },
  {
    id: 'store-celestial-pin-set',
    name: 'Celestial Order Enamel Pin Set',
    slug: 'celestial-order-enamel-pin-set',
    tagline: 'Six-pin collector set with metallic constellation finishes.',
    description:
      'Pocket-friendly collectible pack crafted with hard enamel and textured details. Ships with numbered collector card and magnetic display strip.',
    price: '$36',
    category: 'Collectibles',
    franchise: 'Celestial Order',
    type: 'Pin Collection',
    image: 'Set of metallic enamel pins arranged in a constellation layout',
    imageAlt: 'Celestial Order enamel pins with collector backing card',
    availability: 'sold-out',
    tags: ['pins', 'limited-run', 'fandom-drop'],
  },
  {
    id: 'store-wave-runners-hoodie',
    name: 'Wave Runners Studio Hoodie',
    slug: 'wave-runners-studio-hoodie',
    tagline: 'Oversized premium hoodie with tonal world-map print.',
    description:
      'Soft brushed interior and subtle in-universe graphics make this an everyday wearable for fans who prefer understated franchise design.',
    price: '$84',
    category: 'Apparel',
    franchise: 'Wave Runners',
    type: 'Hoodie',
    image: 'Oversized charcoal hoodie with subtle tonal graphic print',
    imageAlt: 'Wave Runners hoodie folded with close-up of sleeve patch',
    availability: 'preorder',
    externalUrl: 'https://shop.example.com/products/wave-runners-studio-hoodie',
    ctaLabel: 'Reserve Drop',
    tags: ['apparel', 'minimalist', 'seasonal-drop'],
  },
];
